---
title: Tooot.im Federation Restrictions and Local Emoji
date: today
date-format: iso
author: aRubes@tooot.im
format:
  html:
    embed-resources: true
    minimal: false
    theme: 
      light: United
      dark: darkly
    highlight-style: github
    page-layout: article
    toc: true
    toc_float: true
    toc-title: Contents
    toc-location: left
    number-sections: false
    anchor-sections: true
    code-fold: true
    code-overflow: wrap
    code-line-numbers: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    search: false
    title-block-banner: true
---

```{r libraries}
#| echo: false
#| output: false

library(reactable)
library(rtoot)
library(dplyr)
```

## Federation Restrictions

```{r Restrictions}
Restrictions <- rtoot::get_instance_blocks("tooot.im")
Restrictions <- Restrictions[, -2]
Restrictions <-
     reactable(
          Restrictions,
          groupBy = "severity",
          filterable = T,
          sortable = T,
          searchable = T,
          defaultPageSize = 30,
          highlight = T,
          striped = T,
          showSortable = T
     ) 

Restrictions
```


## Local Emoji

::: callout-tip
## Tip

Be sure to add ':' before and after the shortcode
:::

```{r emojis}
emojis <-
     get_instance_emoji("tooot.im") |> relocate("category") |> arrange(category)
emojis <- emojis |> reactable(
     columns = list(
       url = colDef(cell = function(value) {
         htmltools::tags$img(src = value, width = "50px", height = "50px")
       }
       )),
     groupBy = "category",
     filterable = T,
     sortable = T,
     searchable = T,
     defaultPageSize = 30,
     highlight = T,
     striped = T,
     showSortable = T
    ) 

emojis
```